name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          game-versions: |
            1.12.2
          java: |
            Java 8
          github-token: ${{ secrets.GITHUB_TOKEN }}
          curseforge-id: "1298387"
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: "A1gJtDBi"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version-type: "beta"